language: cpp
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - build-essential
    - gawk
    - ccache
    - genromfs
    - libc6-i386
    - python-pip
    - python-dev
    - zlib1g-dev
    - gcc-4.9
    - g++-4.9
    - cmake
    - cmake-data
cache:
  ccache: true
  directories:
  - $HOME/opt
before_install:
- Tools/scripts/configure-ci.sh
script:
- pushd ..
- git clone https://github.com/3drobotics/PX4Firmware-solo.git
- mv ./PX4Firmware-solo ./PX4Firmware
- git clone https://github.com/3drobotics/PX4NuttX.git
- popd
- . ~/.profile
- pushd ArduCopter
- make configure
- make px4-v2
before_cache:
- ccache -z
compiler:
- gcc
deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: S3M/mXvbc5OcJsqhKmbMa9pvjJ8P/wph9iEFU/nVVCl/yCIW4nzyftK9UcHaCGJDLxdrKWGOZhwd+gTQNcFtTh8pHd5kXwqeF33//qlumHp4k1LPQFSmYea0yKHl3pTejeVxjS4yJ9lms3dIwLL+io/owKjMJY2j/4WGeo6UK7T5M2vn4tY+7A9IeA3DG3l36OsLGBCOAj/kObmNE8ru7lWQWl7EBIqn1EKwqU/TBWL4Z018uADB0GRAmoCHHMtB5dIj93tuS3fOD3dpEOH/cIjNN8AQ2/OK8qVNv+NZuxtjNECX6hMW22UXcJVSGIE5iTqpx2RQWEiQjTu8w6OIe6IauwTO1HCBzTBC2jrHkTEfTRs0jm/JJbjywCa0mZMxaSxf6BRuf3BgIIwes2Xw00eK9UtFvuevsYN6WJuXmYf83zRxZwPW6tChK4lDv9BDb2YMWu7OE0KOZQG7U2dNJxxnCkXl4xVmRC3yPpjtng5gIiIszpHSqa68pMNA+lwBpc9eDngKaRnyeRlEc0qXHn7o6JJmYxrBdNJJbxZqzhUazDo/xicOeEYiKLjuWtVUzuXyQRQMlWPKYExuoQadEmj7IpTqN4PPoWL7Moe5eozBwnMa4aROZQTLxDzl8y7M0L4eIZX/FwiXXisiO39D8eTnziGF20njYKr7KO5A8wQ=
  file: 'ArduCopter-v2.px4'
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
notifications:
  email:
    on_success: always
    on_failure: always

 
